name: card_game
description: "A new Flutter project."
repository: https://github.com/JLogical-Apps/card_game
issue_tracker: https://github.com/JLogical-Apps/card_game/issues

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter_hooks: ^0.21.1-pre.4
  playing_cards: ^0.4.1+11
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true