name: card_game
description: A declarative Flutter package for building card games with drag-and-drop support and fluid animations. Includes flexible layouts, standard playing cards and custom cards support, plus example implementations like Solitaire and War.
repository: https://github.com/JLogical-Apps/card_game
issue_tracker: https://github.com/JLogical-Apps/card_game/issues

version: 1.0.0

screenshots:
  - path: screenshots/tower_of_hanoi.gif
    description: Tower of Hanoi
  - path: screenshots/war.gif
    description: War
  - path: screenshots/memory_match.gif
    description: Memory Match
  - path: screenshots/golf_solitaire.gif
    description: Golf Solitaire
  - path: screenshots/solitaire.gif
    description: Solitaire

topics:
  - flutter
  - widget
  - ui

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter_hooks: ^0.20.5
  playing_cards: ^0.4.1+11
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true