name: card_game
description: A declarative Flutter package for building card games with drag-and-drop, animations, and flexible layouts. Examples include Solitaire and War.
repository: https://github.com/JLogical-Apps/card_game
issue_tracker: https://github.com/JLogical-Apps/card_game/issues

version: 1.1.1

screenshots:
  - path: screenshots/tower_of_hanoi.gif
    description: Gameplay of Tower of Hanoi
  - path: screenshots/war.gif
    description: Gameplay of War
  - path: screenshots/memory_match.gif
    description: Gameplay of Memory Match
  - path: screenshots/golf_solitaire.gif
    description: Gameplay of Golf Solitaire
  - path: screenshots/solitaire.gif
    description: Gameplay of Solitaire

topics:
  - flutter
  - widget
  - ui

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  equatable: ^2.0.7
  provider: ^6.1.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/